import { featureChecks } from "./feature-checks.mjs";
import { Pool } from 'pg';
import { readFile,readdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { randomUUID,createHash } from 'node:crypto';
const connectionString=process.env.TEST_DATABASE_URL;
if(!connectionString)throw new Error('Set TEST_DATABASE_URL to a disposable PostGIS database named sheaf_test_*.');
if(!new URL(connectionString).pathname.startsWith('/sheaf_test_'))throw new Error('Refusing to test in a non-test database. Use sheaf_test_* as the database name.');
const pool=new Pool({connectionString,max:10});let passed=0;
const q=(sql,args=[])=>pool.query(sql,args);
async function test(name,fn){await fn();passed++;console.log(`PASS ${name}`);}
async function role(name,sql,args=[],uid=''){const c=await pool.connect();try{await c.query(`set role ${name}`);await c.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);return await c.query(sql,args);}finally{await c.query('reset role');c.release();}}
const org=randomUUID(),otherOrg=randomUUID(),staff=randomUUID();
const hash=s=>createHash('sha256').update(s).digest('hex');
async function vol(tags=['goods'],frequency='instant',organization=org){const id=randomUUID();await q("insert into volunteers(id,organization_id,name,email,capability_tags,frequency,geolocation) values($1,$2,'Test volunteer',$3,$4,$5,'SRID=4326;POINT(-77.86 40.79)')",[id,organization,`${id}@example.org`,tags,frequency]);return id;}
async function need(status='open',urgency='critical',organization=org){const id=randomUUID();await q("insert into needs(id,organization_id,title,category,description,urgency,service_area,ways_to_help,capability_tags,needed_by,status,approved_at,geolocation) values($1,$2,'Test need','goods','Test only',$3,'Centre',array['Donate'],array['goods'],now()+interval '10 days',$4,now(),'SRID=4326;POINT(-77.85 40.80)')",[id,organization,urgency,status]);return id;}
try{
 const exists=await q("select to_regclass('public.organizations') as present");assert.equal(exists.rows[0].present,null,'Use a new empty database for each run.');
 await q("do $$ begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin; end if; if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin; end if; if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role nologin bypassrls; end if; end $$;");
 await q("create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to anon,authenticated,service_role;");
 for(const file of (await readdir('supabase/migrations')).sort())await q(await readFile(`supabase/migrations/${file}`,'utf8'));
 await q("grant usage on schema public,extensions to anon,authenticated,service_role");
 await q("insert into auth.users values($1)",[staff]);
 await q("insert into organizations(id,name,service_area,contact_email) values($1,'Test org','PA','care@example.org'),($2,'Other org','PA','other@example.org')",[org,otherOrg]);
 await q("insert into organization_members values($1,$2,'admin')",[org,staff]);
 const a=await vol(),b=await vol(),outsider=await vol(['goods'],'instant',otherOrg),nonOpen=await need('claimed'),open=await need();
 await test('public feed exposes open needs but not non-open needs',async()=>{const r=await role('anon','select id from needs');assert(r.rows.some(n=>n.id===open));assert(!r.rows.some(n=>n.id===nonOpen));});
 await test('anonymous clients cannot read private geolocation or volunteers',async()=>{await assert.rejects(role('anon','select geolocation from needs'),/permission denied/);await assert.rejects(role('anon','select email from volunteers'),/permission denied/);});
 await test('ordinary authenticated users cannot see volunteer identities',async()=>{assert.equal((await role('authenticated','select email from volunteers')).rowCount,0);});
 await test('staff access is organization scoped',async()=>{const r=await role('authenticated','select id from volunteers',[],staff);assert.equal(r.rowCount,2);assert(!r.rows.some(v=>v.id===outsider));});
 await test('privileged claim RPC cannot be called by anonymous users',async()=>{await assert.rejects(role('anon','select claim_need($1,$2,$3,$4)',[org,open,a,'Donate']),/permission denied/);});
 await test('pending needs are no longer a valid state',async()=>{await assert.rejects(need('pending'),/needs_status_check/);});
 await test('cross-organization volunteer cannot claim a need',async()=>{await assert.rejects(q('select claim_need($1,$2,$3,$4)',[org,open,outsider,'Donate']),/foreign key/);});
 await test('invalid help option cannot claim a need',async()=>{await assert.rejects(q('select claim_need($1,$2,$3,$4)',[org,open,a,'Anything']),/listed way/);});
 await test('concurrent claims have exactly one winner',async()=>{const results=await Promise.allSettled([q('select claim_need($1,$2,$3,$4)',[org,open,a,'Donate']),q('select claim_need($1,$2,$3,$4)',[org,open,b,'Donate'])]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await q('select id from claims where need_id=$1',[open])).rowCount,1);});
 const winner=(await q('select volunteer_id,id from claims where need_id=$1',[open])).rows[0];
 await test('repeat claims by the winner are idempotent',async()=>{const r=await q('select claim_need($1,$2,$3,$4) id',[org,open,winner.volunteer_id,'Donate']);assert.equal(r.rows[0].id,winner.id);assert.equal((await q("select id from notifications where kind='claim_confirmation'")).rowCount,1);});
 await test('approved staff roles include coordinators and assistants',async()=>{const coordinator=randomUUID(),assistant=randomUUID();await q('insert into auth.users values($1),($2)',[coordinator,assistant]);await q("insert into organization_members values($1,$2,'county_coordinator'),($1,$3,'assistant')",[org,coordinator,assistant]);assert.equal((await q('select count(*)::int count from organization_members where user_id in ($1,$2)',[coordinator,assistant])).rows[0].count,2);});
 await test('completion updates both need and claim history',async()=>{await q('select confirm_delivery($1,$2,$3,$4)',[org,winner.id,staff,1]);assert((await q('select completed_at from claims where need_id=$1',[open])).rows[0].completed_at);});
 await test('expired and reused magic links are rejected',async()=>{const h=hash('expired');await q("insert into magic_links(token_hash,organization_id,email,name,expires_at) values($1,$2,'test@example.org','Test',now()-interval '1 minute')",[h,org]);await assert.rejects(q('select redeem_magic_link($1,$2,$3)',[org,h,hash('session')]),/expired/);await q("update magic_links set expires_at=now()+interval '10 minutes' where token_hash=$1",[h]);await q('select redeem_magic_link($1,$2,$3)',[org,h,hash('session')]);await assert.rejects(q('select redeem_magic_link($1,$2,$3)',[org,h,hash('session2')]),/already been used/);});
 await test('losing a claim does not consume the magic link or create a session',async()=>{const h=hash('lost');await q("insert into magic_links(token_hash,organization_id,email,name,need_id,way,expires_at) values($1,$2,'lost@example.org','Test',$3,'Donate',now()+interval '10 minutes')",[h,org,open]);await assert.rejects(q('select redeem_magic_link($1,$2,$3)',[org,h,hash('lost-session')]),/no longer available/);assert.equal((await q('select consumed_at from magic_links where token_hash=$1',[h])).rows[0].consumed_at,null);assert.equal((await q('select * from volunteer_sessions where token_hash=$1',[hash('lost-session')])).rowCount,0);});
 await test('PostGIS returns distance and truthful capability/history reasons',async()=>{const r=await q('select * from score_matches($1,$2)',[org,winner.volunteer_id]);assert(r.rows[0].distance>0);assert(r.rows[0].reasons.includes('Fits how you like to help'));assert(r.rows[0].reasons.includes('Builds on your past help'));});
 await test('rate limit increments are atomic under concurrency',async()=>{const r=await Promise.all(Array.from({length:8},()=>q("select take_rate_limit('test',3,3600) allowed")));assert.equal(r.filter(x=>x.rows[0].allowed).length,3);});
 // Isolate notification fixtures from earlier workflows.
 await q("update needs set next_wave_at=now()+interval '1 year' where organization_id=$1",[org]);
 const waveNeed=await need();for(let i=0;i<10;i++)await vol();
 await test('first wave notifies only the top three',async()=>{await q('select refresh_matches($1)',[org]);await q('select prepare_waves($1)',[org]);assert.equal((await q("select * from notifications where need_id=$1 and kind='match'",[waveNeed])).rowCount,3);});
 await test('critical wave waits 15 minutes and widens by six',async()=>{const n=(await q('select next_wave_at from needs where id=$1',[waveNeed])).rows[0];assert(n.next_wave_at.getTime()>Date.now()+14*60000);await q('select prepare_waves($1)',[org]);assert.equal((await q("select * from notifications where need_id=$1 and kind='match'",[waveNeed])).rowCount,3);await q("update needs set next_wave_at=now()-interval '1 minute' where id=$1",[waveNeed]);await q('select prepare_waves($1)',[org]);assert.equal((await q("select * from notifications where need_id=$1 and kind='match'",[waveNeed])).rowCount,9);});
 await test('claiming a need cancels queued match messages',async()=>{await q('select claim_need($1,$2,$3,$4)',[org,waveNeed,a,'Donate']);assert.equal((await q("select * from notifications where need_id=$1 and kind='match' and status='queued'",[waveNeed])).rowCount,0);});
 const digest=await vol(['goods'],'digest');
 await q("update volunteers set frequency='off' where id<>$1 and organization_id=$2",[digest,org]);
 await need('open','flexible');await need('open','soon');
 await test('digest groups selected needs into one scheduled email',async()=>{await q('select refresh_matches($1)',[org]);await q('select prepare_waves($1)',[org]);const rows=(await q("select * from notifications where volunteer_id=$1 and kind='digest'",[digest])).rows;assert.equal(rows.length,1);assert.equal(rows[0].payload.need_ids.length,2);assert(rows[0].send_after>Date.now());});
 await test('digest and instantaneous sends share the rolling-day cap',async()=>{await q("update volunteers set daily_cap=1 where id=$1",[digest]);await q("insert into notifications(organization_id,volunteer_id,kind,dedupe_key,status,sent_at) values($1,$2,'match','earlier','sent',now())",[org,digest]);await q("update notifications set status='sending' where volunteer_id=$1 and kind='digest'",[digest]);const id=(await q("select id from notifications where volunteer_id=$1 and kind='digest'",[digest])).rows[0].id;assert.equal((await q('select delivery_allowed($1,$2) allowed',[org,id])).rows[0].allowed,false);});
 await test('anonymous users cannot redeem tokens through the database API',async()=>{await assert.rejects(role('anon','select redeem_magic_link($1,$2,$3)',[org,hash('x'),hash('y')]),/permission denied/);});
 await test('automatic reminders wait 48 hours and deduplicate by need/day',async()=>{await q("update claims set created_at=now()-interval '3 days' where need_id=$1",[waveNeed]);await q("update volunteers set daily_cap=1 where id=$1",[a]);assert.equal((await q('select prepare_reminders($1) count',[org])).rows[0].count,1);assert.equal((await q('select prepare_reminders($1) count',[org])).rows[0].count,0);assert.equal((await q("select id from notifications where need_id=$1 and kind='reminder'",[waveNeed])).rowCount,1);});
 await test('incompatible availability never receives an outreach wave',async()=>{await q("update volunteers set frequency='off' where organization_id=$1",[org]);const timed=await need();const available=await vol();await q("update needs set window_start=now()+interval '1 day',window_end=now()+interval '1 day 1 hour' where id=$1",[timed]);await q("update volunteers set availability=jsonb_build_array(jsonb_build_object('start',now()+interval '3 days','end',now()+interval '3 days 1 hour')) where id=$1",[available]);await q('select refresh_matches($1)',[org]);await q('select prepare_waves($1)',[org]);assert.equal((await q('select id from notifications where need_id=$1 and volunteer_id=$2',[timed,available])).rowCount,0);});
 await test('concurrent workers never reserve the same queue item',async()=>{const [x,y]=await Promise.all([q('select * from reserve_notifications($1)',[org]),q('select * from reserve_notifications($1)',[org])]);const ids=[...x.rows,...y.rows].map(n=>n.id);assert(ids.length>0);assert.equal(new Set(ids).size,ids.length);});
 await test('a worker crash on its final attempt becomes a visible failure',async()=>{await q("insert into notifications(organization_id,volunteer_id,kind,dedupe_key,status,attempts,lease_until) values($1,$2,'match','crashed-final','sending',5,now()-interval '1 minute')",[org,a]);await q('select * from reserve_notifications($1)',[org]);assert.equal((await q("select status from notifications where dedupe_key='crashed-final'")).rows[0].status,'failed');});
 await featureChecks({q,test,role,org,otherOrg,staff,need,vol});
 console.log(`\n${passed} database integration checks passed.`);
}finally{await pool.end();}
